import { PropertyFormValues } from '../../../types/property';

export const PROPERTY_FORM_INITIAL_VALUES: PropertyFormValues = {
  title: '',
  type: '',
  size: '',
  description: '',
  price: '',
  bedrooms: '',
  bathrooms: '',
  city: '',
  address: '',
  amenities: [],
  images: [],
};

export const AMENITIES = [
  { icon: '🏊', label: 'Pool', value: 'pool' },
  { icon: '💪', label: 'Gym', value: 'gym' },
  { icon: '🚗', label: 'Parking', value: 'parking' },
  { icon: '🛗', label: 'Elevator', value: 'elevator' },
  { icon: '🌱', label: 'Garden', value: 'garden' },
  { icon: '🪟', label: 'Balcony', value: 'balcony' },
  { icon: '🪑', label: 'Terrace', value: 'terrace' },
  { icon: '❄️', label: 'Air Conditioning', value: 'air_conditioning' },
  { icon: '🔥', label: 'Heating', value: 'heating' },
  { icon: '🛜', label: 'WiFi', value: 'wifi' },
  { icon: '🔒', label: 'Security System', value: 'security_system' },
  { icon: '👁️', label: 'CCTV', value: 'cctv' },
  { icon: '🔥', label: 'Fireplace', value: 'fireplace' },
  { icon: '🛋️', label: 'Furnished', value: 'furnished' },
  { icon: '🍳', label: 'Kitchen Equipped', value: 'kitchen_equipped' },
  { icon: '🧊', label: 'Refrigerator', value: 'refrigerator' },
  { icon: '🧺', label: 'Washing Machine', value: 'washing_machine' },
  { icon: '🍽️', label: 'Dishwasher', value: 'dishwasher' },
  { icon: '🔥', label: 'Microwave', value: 'microwave' },
  { icon: '📦', label: 'Storage Room', value: 'storage_room' },
  { icon: '🪜', label: 'Basement', value: 'basement' },
  {
    icon: '♿️',
    label: 'Wheelchair Accessible',
    value: 'wheelchair_accessible',
  },
  { icon: '👨‍💼', label: 'Concierge', value: 'concierge' },
  { icon: '🧸', label: 'Playground', value: 'playground' },
  { icon: '🔥', label: 'BBQ Area', value: 'bbq_area' },
  { icon: '☀️', label: 'Solar Panels', value: 'solar_panels' },
];
